//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauSach
    {
        public int MaDauSach { get; set; }
        public Nullable<int> SoKiemSoat { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
        public string GhiChu { get; set; }
    }
}
