//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<int> MaNhaXuatBan { get; set; }
        public Nullable<int> MaDauSach { get; set; }
    }
}
