//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheThuVien
    {
        public string MaThe { get; set; }
        public Nullable<int> MaChiTietTheTV { get; set; }
        public Nullable<int> MaTinhTrangSD { get; set; }
        public string Password { get; set; }
    }
}
